require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "test/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation: 
  Enabled: false

Style/FrozenStringLiteralComment: 
  Enabled: false

Style/ClassAndModuleChildren: 
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
    "%w": "()"