{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/authors": {
      "get": {
        "summary": "list authors",
        "tags": [
          "Authors"
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Author"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create Author",
        "tags": [
          "Authors"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Author"
              }
            }
          }
        }
      }
    },
    "/api/v1/authors/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "author id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "show author",
        "tags": [
          "Authors"
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Author"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "update author",
        "tags": [
          "Authors"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "successful"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Author"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete author",
        "tags": [
          "Authors"
        ],
        "responses": {
          "204": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/competencies": {
      "get": {
        "summary": "list competencies",
        "tags": [
          "Competencies"
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Competency"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create Competency",
        "tags": [
          "Competencies"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Competency"
              }
            }
          }
        }
      }
    },
    "/api/v1/competencies/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "competency id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "show competency",
        "tags": [
          "Competencies"
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Competency"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "update competency",
        "tags": [
          "Competencies"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "successful"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Competency"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete competency",
        "tags": [
          "Competencies"
        ],
        "responses": {
          "204": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/courses": {
      "get": {
        "summary": "list courses",
        "tags": [
          "Courses"
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CourseWithRelations"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "create course",
        "tags": [
          "Courses"
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "created"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Course"
              }
            }
          }
        }
      }
    },
    "/api/v1/courses/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "course id",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "show course",
        "tags": [
          "Courses"
        ],
        "responses": {
          "200": {
            "description": "successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CourseWithRelations"
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "update course",
        "tags": [
          "Courses"
        ],
        "parameters": [

        ],
        "responses": {
          "200": {
            "description": "successful"
          },
          "422": {
            "description": "unprocessable entity"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Course"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "delete course",
        "tags": [
          "Courses"
        ],
        "responses": {
          "204": {
            "description": "successful"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Course": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for course"
          },
          "title": {
            "type": "string",
            "description": "Title of course"
          },
          "description": {
            "type": "string",
            "description": "Description of course"
          },
          "created_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the competency was created"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the competency was created"
          }
        }
      },
      "CourseWithRelations": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for course"
          },
          "title": {
            "type": "string",
            "description": "Title of course"
          },
          "description": {
            "type": "string",
            "description": "Description of course"
          },
          "created_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the competency was created"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the competency was created"
          },
          "author": {
            "$ref": "#/components/schemas/Author"
          },
          "competencies": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Competency"
            }
          }
        }
      },
      "Author": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for author"
          },
          "name": {
            "type": "string",
            "description": "Name of author"
          },
          "email": {
            "type": "string",
            "description": "Email of author"
          },
          "created_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the author was created"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the author was updated"
          }
        }
      },
      "Competency": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Unique identifier for competency"
          },
          "name": {
            "type": "string",
            "description": "Name of competency"
          },
          "created_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the competency was created"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp when the competency was updated"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "localhost:3000"
        }
      }
    }
  ]
}